// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app.sql

package postgresdb

import (
	"context"
)

const createDocument = `-- name: CreateDocument :execrows
INSERT INTO documents (workspace_id, document_id, ciphertext, ciphertext_hash, revision, deleted, imported_legacy)
VALUES ($1, $2, $3, $4, 1, $5, $6)
ON CONFLICT (workspace_id, document_id) DO NOTHING
`

type CreateDocumentParams struct {
	WorkspaceID    string
	DocumentID     string
	Ciphertext     string
	CiphertextHash string
	Deleted        bool
	ImportedLegacy bool
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDocument,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.Ciphertext,
		arg.CiphertextHash,
		arg.Deleted,
		arg.ImportedLegacy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createWorkspace = `-- name: CreateWorkspace :execrows
INSERT INTO workspaces (id, kdf_version, kdf_salt, kdf_memory, kdf_iterations, kdf_parallelism, auth_public_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
`

type CreateWorkspaceParams struct {
	ID             string
	KdfVersion     int32
	KdfSalt        string
	KdfMemory      int32
	KdfIterations  int32
	KdfParallelism int32
	AuthPublicKey  string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.KdfVersion,
		arg.KdfSalt,
		arg.KdfMemory,
		arg.KdfIterations,
		arg.KdfParallelism,
		arg.AuthPublicKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePublication = `-- name: DeletePublication :execrows
DELETE FROM publications WHERE workspace_id = $1 AND document_id = $2
`

type DeletePublicationParams struct {
	WorkspaceID string
	DocumentID  string
}

func (q *Queries) DeletePublication(ctx context.Context, arg DeletePublicationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePublication, arg.WorkspaceID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocument = `-- name: GetDocument :one
SELECT workspace_id, document_id, ciphertext, ciphertext_hash, revision, deleted, imported_legacy, updated_at
FROM documents WHERE workspace_id = $1 AND document_id = $2
`

type GetDocumentParams struct {
	WorkspaceID string
	DocumentID  string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.WorkspaceID, arg.DocumentID)
	var i Document
	err := row.Scan(
		&i.WorkspaceID,
		&i.DocumentID,
		&i.Ciphertext,
		&i.CiphertextHash,
		&i.Revision,
		&i.Deleted,
		&i.ImportedLegacy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT public_id, workspace_id, document_id, title, content, content_mode, legacy, updated_at
FROM publications WHERE public_id = $1
`

func (q *Queries) GetPublication(ctx context.Context, publicID string) (Publication, error) {
	row := q.db.QueryRowContext(ctx, getPublication, publicID)
	var i Publication
	err := row.Scan(
		&i.PublicID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.Title,
		&i.Content,
		&i.ContentMode,
		&i.Legacy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicationByDocument = `-- name: GetPublicationByDocument :one
SELECT public_id, workspace_id, document_id, title, content, content_mode, legacy, updated_at
FROM publications WHERE workspace_id = $1 AND document_id = $2
`

type GetPublicationByDocumentParams struct {
	WorkspaceID string
	DocumentID  string
}

func (q *Queries) GetPublicationByDocument(ctx context.Context, arg GetPublicationByDocumentParams) (Publication, error) {
	row := q.db.QueryRowContext(ctx, getPublicationByDocument, arg.WorkspaceID, arg.DocumentID)
	var i Publication
	err := row.Scan(
		&i.PublicID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.Title,
		&i.Content,
		&i.ContentMode,
		&i.Legacy,
		&i.UpdatedAt,
	)
	return i, err
}

const getStagedLegacyPublication = `-- name: GetStagedLegacyPublication :one
SELECT public_id, legacy_id, document_id, title, content, content_mode, imported_at
FROM legacy_publications WHERE public_id = $1
`

func (q *Queries) GetStagedLegacyPublication(ctx context.Context, publicID string) (LegacyPublication, error) {
	row := q.db.QueryRowContext(ctx, getStagedLegacyPublication, publicID)
	var i LegacyPublication
	err := row.Scan(
		&i.PublicID,
		&i.LegacyID,
		&i.DocumentID,
		&i.Title,
		&i.Content,
		&i.ContentMode,
		&i.ImportedAt,
	)
	return i, err
}

const getStagedLegacyWorkspace = `-- name: GetStagedLegacyWorkspace :one
SELECT legacy_id, migrated_workspace_id, imported_at
FROM legacy_workspaces WHERE legacy_id = $1
`

func (q *Queries) GetStagedLegacyWorkspace(ctx context.Context, legacyID string) (LegacyWorkspace, error) {
	row := q.db.QueryRowContext(ctx, getStagedLegacyWorkspace, legacyID)
	var i LegacyWorkspace
	err := row.Scan(&i.LegacyID, &i.MigratedWorkspaceID, &i.ImportedAt)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, kdf_version, kdf_salt, kdf_memory, kdf_iterations, kdf_parallelism, auth_public_key, created_at, updated_at
FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.KdfVersion,
		&i.KdfSalt,
		&i.KdfMemory,
		&i.KdfIterations,
		&i.KdfParallelism,
		&i.AuthPublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT workspace_id, document_id, ciphertext, ciphertext_hash, revision, deleted, imported_legacy, updated_at
FROM documents WHERE workspace_id = $1 ORDER BY document_id
`

func (q *Queries) ListDocuments(ctx context.Context, workspaceID string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.DocumentID,
			&i.Ciphertext,
			&i.CiphertextHash,
			&i.Revision,
			&i.Deleted,
			&i.ImportedLegacy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedLegacyDocuments = `-- name: ListStagedLegacyDocuments :many
SELECT legacy_id, document_id, ciphertext, document_hash, imported_at
FROM legacy_documents WHERE legacy_id = $1 ORDER BY document_id
`

func (q *Queries) ListStagedLegacyDocuments(ctx context.Context, legacyID string) ([]LegacyDocument, error) {
	rows, err := q.db.QueryContext(ctx, listStagedLegacyDocuments, legacyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegacyDocument
	for rows.Next() {
		var i LegacyDocument
		if err := rows.Scan(
			&i.LegacyID,
			&i.DocumentID,
			&i.Ciphertext,
			&i.DocumentHash,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putPublication = `-- name: PutPublication :exec
INSERT INTO publications (public_id, workspace_id, document_id, title, content, content_mode, legacy)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (public_id) DO UPDATE SET
    title = EXCLUDED.title, content = EXCLUDED.content, content_mode = EXCLUDED.content_mode,
    updated_at = CURRENT_TIMESTAMP
WHERE publications.workspace_id = EXCLUDED.workspace_id
  AND publications.document_id = EXCLUDED.document_id
`

type PutPublicationParams struct {
	PublicID    string
	WorkspaceID string
	DocumentID  string
	Title       string
	Content     string
	ContentMode string
	Legacy      bool
}

func (q *Queries) PutPublication(ctx context.Context, arg PutPublicationParams) error {
	_, err := q.db.ExecContext(ctx, putPublication,
		arg.PublicID,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.Title,
		arg.Content,
		arg.ContentMode,
		arg.Legacy,
	)
	return err
}

const rotateDocument = `-- name: RotateDocument :execrows
UPDATE documents SET ciphertext = $3, ciphertext_hash = $4, revision = revision + 1, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = $1 AND document_id = $2 AND revision = $5 AND deleted = FALSE
`

type RotateDocumentParams struct {
	WorkspaceID    string
	DocumentID     string
	Ciphertext     string
	CiphertextHash string
	Revision       int64
}

func (q *Queries) RotateDocument(ctx context.Context, arg RotateDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rotateDocument,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.Ciphertext,
		arg.CiphertextHash,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rotateWorkspace = `-- name: RotateWorkspace :execrows
UPDATE workspaces SET kdf_salt = $2, kdf_memory = $3, kdf_iterations = $4, kdf_parallelism = $5,
    auth_public_key = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND auth_public_key = $7
`

type RotateWorkspaceParams struct {
	ID              string
	KdfSalt         string
	KdfMemory       int32
	KdfIterations   int32
	KdfParallelism  int32
	AuthPublicKey   string
	AuthPublicKey_2 string
}

func (q *Queries) RotateWorkspace(ctx context.Context, arg RotateWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rotateWorkspace,
		arg.ID,
		arg.KdfSalt,
		arg.KdfMemory,
		arg.KdfIterations,
		arg.KdfParallelism,
		arg.AuthPublicKey,
		arg.AuthPublicKey_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDocument = `-- name: UpdateDocument :execrows
UPDATE documents
SET ciphertext = $3, ciphertext_hash = $4, revision = revision + 1, deleted = $5, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = $1 AND document_id = $2 AND revision = $6 AND deleted = FALSE
`

type UpdateDocumentParams struct {
	WorkspaceID    string
	DocumentID     string
	Ciphertext     string
	CiphertextHash string
	Deleted        bool
	Revision       int64
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDocument,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.Ciphertext,
		arg.CiphertextHash,
		arg.Deleted,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
