// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"database/sql"
	"time"
)

type Document struct {
	WorkspaceID    string
	DocumentID     string
	Ciphertext     string
	CiphertextHash string
	Revision       int64
	Deleted        bool
	ImportedLegacy bool
	UpdatedAt      time.Time
}

type LegacyDocument struct {
	LegacyID     string
	DocumentID   string
	Ciphertext   string
	DocumentHash string
	ImportedAt   time.Time
}

type LegacyPublication struct {
	PublicID    string
	LegacyID    sql.NullString
	DocumentID  sql.NullString
	Title       string
	Content     string
	ContentMode string
	ImportedAt  time.Time
}

type LegacyWorkspace struct {
	LegacyID            string
	MigratedWorkspaceID sql.NullString
	ImportedAt          time.Time
}

type Publication struct {
	PublicID    string
	WorkspaceID string
	DocumentID  string
	Title       string
	Content     string
	ContentMode string
	Legacy      bool
	UpdatedAt   time.Time
}

type Workspace struct {
	ID             string
	KdfVersion     int32
	KdfSalt        string
	KdfMemory      int32
	KdfIterations  int32
	KdfParallelism int32
	AuthPublicKey  string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
