// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"context"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (int64, error)
	DeletePublication(ctx context.Context, arg DeletePublicationParams) (int64, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
	GetPublication(ctx context.Context, publicID string) (Publication, error)
	GetPublicationByDocument(ctx context.Context, arg GetPublicationByDocumentParams) (Publication, error)
	GetStagedLegacyPublication(ctx context.Context, publicID string) (LegacyPublication, error)
	GetStagedLegacyWorkspace(ctx context.Context, legacyID string) (LegacyWorkspace, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	ListDocuments(ctx context.Context, workspaceID string) ([]Document, error)
	ListStagedLegacyDocuments(ctx context.Context, legacyID string) ([]LegacyDocument, error)
	PutPublication(ctx context.Context, arg PutPublicationParams) error
	RotateDocument(ctx context.Context, arg RotateDocumentParams) (int64, error)
	RotateWorkspace(ctx context.Context, arg RotateWorkspaceParams) (int64, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
