// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type Document struct {
	WorkspaceID    string
	DocumentID     string
	Ciphertext     string
	CiphertextHash string
	Revision       int64
	Deleted        int64
	ImportedLegacy int64
	UpdatedAt      string
}

type LegacyDocument struct {
	LegacyID     string
	DocumentID   string
	Ciphertext   string
	DocumentHash string
	ImportedAt   string
}

type LegacyPublication struct {
	PublicID    string
	LegacyID    sql.NullString
	DocumentID  sql.NullString
	Title       string
	Content     string
	ContentMode string
	ImportedAt  string
}

type LegacyWorkspace struct {
	LegacyID            string
	MigratedWorkspaceID sql.NullString
	ImportedAt          string
}

type Publication struct {
	PublicID    string
	WorkspaceID string
	DocumentID  string
	Title       string
	Content     string
	ContentMode string
	Legacy      int64
	UpdatedAt   string
}

type Workspace struct {
	ID             string
	KdfVersion     int64
	KdfSalt        string
	KdfMemory      int64
	KdfIterations  int64
	KdfParallelism int64
	AuthPublicKey  string
	CreatedAt      string
	UpdatedAt      string
}
